import { User } from './interface/userInterface';

export const USERS: User[] = [
    {
        id: '1',
        firstName: 'Cordy',
        lastName: 'Scudamore',
        age: 22,
        login: 'cscudamore0@va.gov',
        password: 'ssdkfjsd',
        isDeleted: true,
    },
    {
        id: '2',
        firstName: 'Ancell',
        lastName: 'Vedekhov',
        age: 24,
        login: 'avedekhov1@bluehost.com',
        password: 'ssdkfjsd',
        isDeleted: false,
    },
    {
        id: '3',
        firstName: 'Seth',
        lastName: 'Phizakarley',
        age: 10,
        login: 'sphizakarley2@prnewswire.com',
        password: 'ssdkfjsd',
        isDeleted: true,
    },
    {
        id: '4',
        firstName: 'Eziechiele',
        lastName: 'Marsham',
        age: 34,
        login: 'emarsham3@multiply.com',
        password: 'ssdkfjsd',
        isDeleted: true,
    },
    {
        id: '5',
        firstName: 'Cristie',
        lastName: 'Roggers',
        age: 25,
        login: 'croggers4@goo.ne.jp',
        password: 'ssdkfjsd',
        isDeleted: true,
    },
    {
        id: '6',
        firstName: 'Alexis',
        lastName: 'Aronoff',
        age: 29,
        login: 'aaronoff5@hao123.com',
        password: 'ssdkfjsd',
        isDeleted: false,
    },
    {
        id: '7',
        firstName: 'Twyla',
        lastName: 'Milam',
        age: 67,
        login: 'tmilam6@cloudflare.com',
        password: 'ssdkfjsd',
        isDeleted: false,
    },
    {
        id: '8',
        firstName: 'Gardener',
        lastName: 'Arunowicz',
        age: 43,
        login: 'garunowicz7@163.com',
        password: 'ssdkfjsd',
        isDeleted: false,
    },
    {
        id: '9',
        firstName: 'Alix',
        lastName: 'Briiginshaw',
        age: 21,
        login: 'abriiginshaw8@wp.com',
        password: 'ssdkfjsd',
        isDeleted: false,
    },
    {
        id: '10',
        firstName: 'Adolpho',
        lastName: 'Elvish',
        age: 13,
        login: 'aelvish9@aol.com',
        password: 'ssdkfjsd',
        isDeleted: true,
    },
];
