export let ACTIVATED_USERS = [
    {
        id: '1',
        firstName: 'Cordy',
        lastName: 'Scudamore',
        age: 22,
        login: 'cscudamore0@va.gov',
        password: 'ssdkfjsd',
        isDeleted: true,
    },
    {
        id: '3',
        firstName: 'Seth',
        lastName: 'Phizakarley',
        age: 10,
        login: 'sphizakarley2@prnewswire.com',
        password: 'ssdkfjsd',
        isDeleted: true,
    },
    {
        id: '4',
        firstName: 'Eziechiele',
        lastName: 'Marsham',
        age: 34,
        login: 'emarsham3@multiply.com',
        password: 'ssdkfjsd',
        isDeleted: true,
    },
    {
        id: '5',
        firstName: 'Cristie',
        lastName: 'Roggers',
        age: 25,
        login: 'croggers4@goo.ne.jp',
        password: 'ssdkfjsd',
        isDeleted: true,
    },
    {
        id: '10',
        firstName: 'Adolpho',
        lastName: 'Elvish',
        age: 13,
        login: 'aelvish9@aol.com',
        password: 'ssdkfjsd',
        isDeleted: true,
    },
];
