export const DEACTIVATED_USERS = [
    {
        id: '2',
        firstName: 'Ancell',
        lastName: 'Vedekhov',
        age: 24,
        login: 'avedekhov1@bluehost.com',
        password: 'ssdkfjsd',
        isDeleted: false,
    },
    {
        id: '6',
        firstName: 'Alexis',
        lastName: 'Aronoff',
        age: 29,
        login: 'aaronoff5@hao123.com',
        password: 'ssdkfjsd',
        isDeleted: false,
    },
    {
        id: '7',
        firstName: 'Twyla',
        lastName: 'Milam',
        age: 67,
        login: 'tmilam6@cloudflare.com',
        password: 'ssdkfjsd',
        isDeleted: false,
    },
    {
        id: '8',
        firstName: 'Gardener',
        lastName: 'Arunowicz',
        age: 43,
        login: 'garunowicz7@163.com',
        password: 'ssdkfjsd',
        isDeleted: false,
    },
    {
        id: '9',
        firstName: 'Alix',
        lastName: 'Briiginshaw',
        age: 21,
        login: 'abriiginshaw8@wp.com',
        password: 'ssdkfjsd',
        isDeleted: false,
    },
];
